[package]
name = "host"
version = "0.1.0"
edition = "2021"

[dependencies]
methods = { path = "../methods" }
risc0-zkvm = { workspace = true }
serde = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }

[build-dependencies]
cc = "1.0"
